### ISSUE TITLE
you add one yet to fix email so you can send as kitchenink

### ISSUE THREAD

**Issue by sxm887** [isangomar/github-for-developers-7#5]

**Comment by isangomar** [comment]
we will need to test this, i can subscribe to you new blog and see what email gets sent as
. have you tried this yet?

**Comment by sxm887** [comment]
THEMES:
https://wordpress.org/themes/great/
https://wordpress.org/themes/hueman/
https://wordpress.org/themes/sociallyviral/
https://wordpress.org/themes/enamag/
https://wordpress.org/themes/skt-magazine/
https://wordpress.org/themes/colormag/
https://wordpress.org/themes/hathor/
